# Prometheus 설정 파일
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # storage node scrape
  - job_name: "storage-node-host"
    static_configs:
      - targets: ["<STORAGE_NODE_SERVER_IP>:9100"]
  - job_name: "storage-node-container"
    static_configs:
      - targets: ["<STORAGE_NODE_SERVER_IP>:8081"] 
  - job_name: "fastify-storage-node"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["<STORAGE_NODE_SERVER_IP>:3000"]

  # Spring Boot Control Plane (Actuator)
  - job_name: "spring-control-plane"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8080"]